techie.generic.chunk-size=100000
techie.generic.file-delimiter=|
techie.generic.file-headers=Business Date,Location Id,Position Date,Position Key Id
techie.generic.filename-pattern=Memphis_Balance_EOD_%s_*.DAT
#techie.generic.outbound-topic=rods-memphis-eod-bal
techie.generic.input-path=C:\\rods-spring-batch-files\\rods-delimited-file-parser-balance-input-files\\
techie.generic.archive-path=C:\\rods-spring-batch-files\\rods-delimited-file-parser-balance-processed-files\\
techie.generic.message-type=Balance
techie.generic.message-key=Position Key Id
techie.generic.message-src=memphis