techie.generic.chunk-size=100000
techie.generic.file-delimiter=|
techie.generic.file-headers=rtoCode,rtoLocation,signalId,signalLocation,lmvCount,mcwgCount,mgvCount,hmvCount,htvCount,timestamp
techie.generic.filename-pattern=India_TrafficData_%s_*.DAT
techie.generic.outbound-topic=traffic_signal_updates_raw
techie.generic.input-path=C:\\final-year-project-spring-batch-files\\delimited-file-parser-traffic-input-files\\
techie.generic.archive-path=C:\\final-year-project-spring-batch-files\\delimited-file-parser-traffic-processed-files\\
techie.generic.message-type=TrafficData
techie.generic.message-key=signalId
techie.generic.message-src=India